@startuml
set namespaceSeparator ::

class "facade::facade.dart::Grinder" {
  -String _type
  +void grind()
}

class "facade::facade.dart::Maker" {
  -String _type
  +void fill()
  +void retrieve()
  +void start()
}

class "facade::facade.dart::Imbiber" {
  -String _beverage
  +void drink()
}

class "facade::facade.dart::MorningFacade" {
  -Imbiber _coffeeDrinker
  -Grinder _coffeeGrinder
  -Maker _coffeeMaker
  +void prepareCoffee()
  +void drinkCoffee()
}

"facade::facade.dart::MorningFacade" o-- "facade::facade.dart::Imbiber"
"facade::facade.dart::MorningFacade" o-- "facade::facade.dart::Grinder"
"facade::facade.dart::MorningFacade" o-- "facade::facade.dart::Maker"


@enduml